import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by NextJs ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex h-screen w-full items-center justify-center my-12">
            <SignedOut >
              <SignIn routing="hash"   />
            </SignedOut>
            <SignedIn >
               {children}
            </SignedIn>
           
          </main> 
        
        </body>
      </html>
    </ClerkProvider>
  );
}
